---
title: ""
date-modified: last-modified
---

## 목표

본 프로그램은 중등 지리 교사의 **지리공간정보를 활용한 AIㆍ디지털 역량**을 실질적으로 함양하고, 그것을 활용한 구체적인 수업 혁신 방안을 모색하는데 주안점이 있다. 교사들은 지리공간정보 교수-학습 역량 강화 연수를 통해 지리공간정보에 기반한 **인터랙티브 교수-학습 웹 앱**을 디자인 및 제작하는 역량을 함양한다. 학생들은 지리공간정보 **체험 캠프**를 통해 LiDAR 및 인터랙티브 교수-학습 웹 앱을 활용한 수업에 참여함으로써 지리공간정보의 중요성을 구체적으로 체험해보는 기회를 갖는다.

## 내용

#### 지리공간정보 교수-학습 역량 강화 연수

-   AIㆍ디지털 전환과 지리 교사의 역량에 대한 이론 강의

-   디지털 저작 도구인 [Quarto](https://quarto.org/)와 오픈소스 프로그래밍 언어인 [R](https://www.r-project.org/)에 대한 기본 실습

-   인터랙티브 교수-학습 웹 앱의 디자인 및 개발 실습: 학교 현장과 양성 기관의 협업

#### 지리공간정보 체험 캠프

-   지리공간정보와 AIㆍ디지털 기술에 대한 이론 강의

-   드론을 활용한 LiDAR 데이터 구득 및 분석에 대한 체험

-   원격탐사 데이터의 탐색 및 분석 체험과 인터랙티브 교수-학습 웹 앱을 활용한 수업 활동 체험

## 일시 및 장소

#### 지리공간정보 교수-학습 역량 강화 연수

-   2025년 7월 28일(월)\~29일(화) 10:00\~17:00

-   서울대학교 사범대학 10동 103호

#### 지리공간정보 체험 캠프

-   2025년 8월 1일(금) 10:00\~17:00

-   서울대학교 사범대학 10동 103호

## 진행

-   프로그램 총괄 및 이론 강의

    -   [이상일 교수](https://sangillee.snu.ac.kr/) ([서울대학교 지리교육과](https://geoedu.snu.ac.kr/))

-   프로그램 평가

    -   이소영 교수 ([가톨릭관동대학교 지리교육과](https://www.cku.ac.kr/geography/index.do))

    -   교사들의 TPACK 함양을 위한 지리공간정보 교수-학습 프로그램 개발

-   인터랙티브 교수-학습 웹 앱 실습

    -   김세창(서울대학교 지리교육과 석사)

    -   김우형(서울대학교 지리교육과 석사과정)

    -   전혜민(서울대학교 지리교육과 석사과정)

-   드론 및 LiDAR 실습

    -   이하은(서울대학교 지리교육과 박사과정)

## **참가자**

-   교사: 수도권 소재 고등학교 지리 교사 7명

-   학생: 수도권 소재 고등학교 학생 15명

## **후원**

-   [국토지리정보원](https://www.ngii.go.kr/)
